/**
 * Bundle docs/roadmap.html into the web app deterministically.
 *
 * The `/roadmap` route serves the self-contained build-roadmap document (generated
 * by the `roadmap` skill at docs/roadmap.html) as raw HTML. The route imports the
 * markup as a bundled string constant so it is inlined into the Next server bundle
 * at build time — there is NO runtime dependency on docs/ (excluded from the Docker
 * build context by .dockerignore) or on the Next standalone file trace.
 *
 * This runs before `next build` (see apps/web package.json "build"):
 *   - docs/roadmap.html present  → refresh the committed generated module.
 *   - docs/roadmap.html ABSENT   → keep the committed module untouched so the build
 *     still succeeds. The Docker context excludes docs/, and Coolify builds from a
 *     git checkout where the skill's output may be untracked, so the committed copy
 *     is the source of truth for the deployed artifact.
 *
 * To update the deployed roadmap after the `roadmap` skill regenerates
 * docs/roadmap.html, run this locally (or `pnpm --filter web build`) and commit the
 * refreshed apps/web/app/roadmap/roadmap-html.generated.ts.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(scriptDir, '..', '..', '..');
const sourceHtml = join(repoRoot, 'docs', 'roadmap.html');
const outFile = join(scriptDir, '..', 'app', 'roadmap', 'roadmap-html.generated.ts');

function rel(p) {
  return relative(repoRoot, p) || p;
}

if (!existsSync(sourceHtml)) {
  if (existsSync(outFile)) {
    console.log(
      `[gen-roadmap] ${rel(sourceHtml)} not in build context — keeping committed ${rel(outFile)}`,
    );
    process.exit(0);
  }
  console.error(
    `[gen-roadmap] ${rel(sourceHtml)} is missing and no committed ${rel(outFile)} exists.`,
  );
  process.exit(1);
}

const html = readFileSync(sourceHtml, 'utf8');
const generated = `// AUTO-GENERATED by apps/web/scripts/gen-roadmap.mjs — DO NOT EDIT.
// Source: docs/roadmap.html (maintained by the \`roadmap\` skill).
// Regenerate + commit after the roadmap changes: pnpm --filter web build.
export const ROADMAP_HTML = ${JSON.stringify(html)};
`;

// Avoid a needless write (keeps the file mtime/diff stable when nothing changed).
const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : '';
if (current !== generated) {
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, generated, 'utf8');
  console.log(`[gen-roadmap] wrote ${rel(outFile)} (${html.length} bytes from ${rel(sourceHtml)})`);
} else {
  console.log(`[gen-roadmap] ${rel(outFile)} already up to date (${html.length} bytes)`);
}
